image: ridehal-toolchain-base:v1.0

stages:
  - start
  - build
  - test

start:
  stage: start
  script:
    - echo "Start ridehal CI jobs ..."
  tags:
    - ridehal-dev
  only:
    - merge_requests
  timeout: 1h


build ridehal:
  stage: build
  script:
    - echo "Start building ridehal"
    - python3 /data/scripts/gitlab-ci/get_build_config.py
    - sh /data/scripts/gitlab-ci/build_package.sh
    - mkdir packages
    - cp /data/packages/ridehal/ridehal-aarch64-*.tar.gz ./packages
  artifacts:
    name: "ridehal-build-packages"
    when: on_success
    expire_in: 3 hours
    paths:
      - packages
  tags:
    - ridehal-dev
  only:
    - merge_requests
  timeout: 1h

