image: ridehal-toolchain-base:v1.0

stages:
  - start
  - build
  - test
  - check
  - pack

start:
  stage: start
  script:
    - echo "Start ridehal CI jobs ..."
    - sh /data/scripts/gitlab-ci/update-ci-data.sh
  tags:
    - ridehal-dev
  rules:
    - if: '$CI_COMMIT_TAG == "master"'
      when: manual
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
      when: always
  timeout: 1h

build ridehal qnx:
  stage: build
  script:
    - echo "Start building ridehal for QNX"
    - python3 /data/scripts/gitlab-ci/get_build_config.py
    - sh /data/scripts/gitlab-ci/build_package_qnx.sh
  tags:
    - ridehal-dev
  rules:
    - if: '$CI_COMMIT_TAG == "master"'
      when: on_success
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
      when: on_success
  timeout: 1h

build ridehal linux:
  stage: build
  script:
    - echo "Start building ridehal for HGY Linux"
    - python3 /data/scripts/gitlab-ci/get_build_config.py
    - sh /data/scripts/gitlab-ci/build_package_linux.sh
  tags:
    - ridehal-dev
  rules:
    - if: '$CI_COMMIT_TAG == "master"'
      when: on_success
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
      when: on_success
  timeout: 1h

build ridehal ubuntu:
  stage: build
  script:
    - echo "Start building ridehal for HGY Ubuntu"
    - python3 /data/scripts/gitlab-ci/get_build_config.py
    - sh /data/scripts/gitlab-ci/build_package_ubuntu.sh
  tags:
    - ridehal-dev
  rules:
    - if: '$CI_COMMIT_TAG == "master"'
      when: on_success
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
      when: on_success
  timeout: 1h

run gtest for qnx:
  stage: test
  script:
    - echo "Start running gtest for qnx"
    - sh /data/scripts/gitlab-ci/run_gtest_host_qnx.sh
    - python3 /data/scripts/gitlab-ci/parse_gtest_output_qnx.py
  tags:
    - ridehal-dev
  rules:
    - if: '$CI_COMMIT_TAG == "master"'
      when: on_success
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
      when: on_success
  allow_failure: true
  timeout: 1h

run gtest for linux:
  stage: test
  script:
    - echo "Start running gtest for linux"
    - sh /data/scripts/gitlab-ci/run_gtest_host_linux.sh
    - python3 /data/scripts/gitlab-ci/parse_gtest_output_linux.py
  tags:
    - ridehal-dev
  rules:
    - if: '$CI_COMMIT_TAG == "master"'
      when: on_success
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
      when: on_success
  allow_failure: true
  timeout: 1h

run gtest for ubuntu:
  stage: test
  script:
    - echo "Start running gtest for ubuntu"
    - sh /data/scripts/gitlab-ci/run_gtest_host_ubuntu.sh
    - python3 /data/scripts/gitlab-ci/parse_gtest_output_ubuntu.py
  tags:
    - ridehal-dev
  rules:
    - if: '$CI_COMMIT_TAG == "master"'
      when: on_success
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
      when: on_success
  allow_failure: true
  timeout: 1h

code static stan:
  stage: check
  script:
    - echo "Start code static scan"
    - sh /data/scripts/gitlab-ci/run_static_scan.sh
  artifacts:
    name: "static-scan-reports"
    when: on_success
    expire_in: 6 hours
    paths:
      - staticScan-reports
  tags:
    - ridehal-dev
  rules:
    - if: '$CI_COMMIT_TAG == "master"'
      when: manual
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
      when: manual
  allow_failure: true
  timeout: 1h

code coverage check:
  stage: check
  script:
    - echo "Start code coverage test"
    - sh /data/scripts/gitlab-ci/run_code_coverage_test.sh
    - cp -r /data/test/gtest/code_coverage/gcov_report .
  artifacts:
    name: "code-coverage-reports"
    when: on_success
    expire_in: 6 hours
    paths:
      - gcov_report
  tags:
    - ridehal-dev
  rules:
    - if: '$CI_COMMIT_TAG == "master"'
      when: manual
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
      when: manual
  allow_failure: true
  timeout: 1h

generate packages:
  stage: pack
  script:
    - echo "Generating ridehal packages"
    - mkdir packages
    - mv /data/packages/ridehal/ridehal-aarch64-*.tar.gz ./packages
  artifacts:
    name: "ridehal-build-packages"
    when: on_success
    expire_in: 6 hours
    paths:
      - packages
  tags:
    - ridehal-dev
  rules:
    - if: '$CI_COMMIT_TAG == "master"'
      when: manual
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
      when: manual
  allow_failure: true
  timeout: 1h

