#!/bin/sh
# Copyright 2024 Qualcomm Technologies, Inc. All rights reserved.
# Confidential & Proprietary.

homedir=`pwd`

cdsp0skeldir="/vendor/dsp/cdsp;/dspfw/image/dsp/cdsp0;/dsplib/image/dsp/cdsp0;/mnt/etc/images;/mnt/etc/images/cdsp0;/mnt/etc/images/dsp;/firmware/image/dsp/cdsp0/;$homedir/lib/dsp"
cdsp1skeldir="/vendor/dsp/cdsp1;/dspfw/image/dsp/cdsp1;/dsplib/image/dsp/cdsp1;/mnt/etc/images;/mnt/etc/images/cdsp1;/mnt/etc/images/dsp;/firmware/image/dsp/cdsp0/;$homedir/lib/dsp"

export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/lib64:/lib:/mnt/lib64:$homedir/lib/:$homedir/lib/runtime
export PATH=$PATH:$homedir/bin
export CDSP_LIBRARY_PATH=$cdsp0skeldir
export CDSP0_LIBRARY_PATH=$cdsp0skeldir
export CDSP1_LIBRARY_PATH=$cdsp1skeldir

if [ -f /usr/lib/libEGL_adreno.so ] ; then
echo setup env for Linux SDL
export SDL_VIDEO_EGL_DRIVER=/usr/lib/libEGL_adreno.so
export SDL_VIDEO_GL_DRIVER=/usr/lib/libGLESv2_adreno.so
fi

$@
