// Copyright 2024 Qualcomm Technologies, Inc. All rights reserved.
// Confidential & Proprietary.
static const char *ColorConvertorCL =
        "__constant float c_YUV2RGBCoeffs_420[5] = { 1.163999557f, 2.017999649f, -0.390999794f,\n"
        "                                                    -0.812999725f, 1.5959997177f };\n"

        "__kernel void NV12_to_RGB( __global const uchar *srcptr, __global uchar *dstptr,\n"
        "int rows,int cols,int inputStride0,int inputHeight0,int inputStride1,int outputStride )\n"
        "{\n"
        "    int x = get_global_id( 0 );\n"
        "    int y = get_global_id( 1 );\n"
        "    if ( x < cols / 2 )\n"
        "    {\n"
        "        if ( y < rows / 2 )\n"
        "        {\n"
        "            __global const uchar *ysrc = srcptr + \n"
        "            mad24( y << 1, inputStride0, ( x << 1 ) );\n"
        "            __global const uchar *usrc = srcptr + inputStride0 * inputHeight0 + \n"
        "            mad24( y, inputStride1, ( x << 1 ) );\n"
        "            __global uchar *dst1 = dstptr + mad24( y << 1, cols * 3, \n"
        "            mad24( x << 1, 3, 0 ) );\n"
        "            __global uchar *dst2 = dst1 + outputStride * 3;\n"
        "            float Y1 = ysrc[0];\n"
        "            float Y2 = ysrc[1];\n"
        "            float Y3 = ysrc[inputStride0];\n"
        "            float Y4 = ysrc[inputStride0 + 1];\n"
        "            float U = ( (float) usrc[0] ) - 128;\n"
        "            float V = ( (float) usrc[1] ) - 128;\n"
        "            __constant float *coeffs = c_YUV2RGBCoeffs_420;\n"
        "            float ruv = fma( coeffs[4], V, 0.5f );\n"
        "            float guv = fma( coeffs[3], V, fma( coeffs[2], U, 0.5f ) );\n"
        "            float buv = fma( coeffs[1], U, 0.5f );\n"
        "            Y1 = max( 0.f, Y1 - 16.f ) * coeffs[0];\n"
        "            dst1[0] = convert_uchar_sat( Y1 + ruv );\n"
        "            dst1[1] = convert_uchar_sat( Y1 + guv );\n"
        "            dst1[2] = convert_uchar_sat( Y1 + buv );\n"
        "            Y2 = max( 0.f, Y2 - 16.f ) * coeffs[0];\n"
        "            dst1[3] = convert_uchar_sat( Y2 + ruv );\n"
        "            dst1[4] = convert_uchar_sat( Y2 + guv );\n"
        "            dst1[5] = convert_uchar_sat( Y2 + buv );\n"
        "            Y3 = max( 0.f, Y3 - 16.f ) * coeffs[0];\n"
        "            dst2[0] = convert_uchar_sat( Y3 + ruv );\n"
        "            dst2[1] = convert_uchar_sat( Y3 + guv );\n"
        "            dst2[2] = convert_uchar_sat( Y3 + buv );\n"
        "            Y4 = max( 0.f, Y4 - 16.f ) * coeffs[0];\n"
        "            dst2[3] = convert_uchar_sat( Y4 + ruv );\n"
        "            dst2[4] = convert_uchar_sat( Y4 + guv );\n"
        "            dst2[5] = convert_uchar_sat( Y4 + buv );\n"
        "        }\n"
        "    }\n"
        "}\n";
